<script>
    let player = "Onur Göksu - onurbey1";
    let commissionRate = "";
    let commissionType = "revenue";
    let network = "website";
    let networkLink = "www.instagram.com/network";
  
    function createAffiliate() {
      console.log({
        player,
        commissionRate,
        commissionType,
        network,
        networkLink,
      });
      // Add your form submission logic here
    }
  
    function cancel() {
      // Reset form or perform cancel action
      player = "Onur Göksu - onurbey1";
      commissionRate = "";
      commissionType = "revenue";
      network = "website";
      networkLink = "www.instagram.com/network";
    }
  </script>
  
  <style>
    .form-container {
        z-index: 1000;
      max-width: 600px;
      margin: auto;
      padding: 20px;
      border: 1px solid #ddd;
      border-radius: 5px;
      background-color: white;
      color: #3d4b51;
    }
  
    .form-group {
      margin-bottom: 15px;
    }
  
    .form-group label {
      display: block;
      margin-bottom: 5px;
      color: #3d4b51;
    }
  
    .form-group input,
    .form-group select {
      width: 100%;
      padding: 10px;
      border: 1px solid #ddd;
      border-radius: 4px;
      background-color: white;
      color: #3d4b51;
    }
  
    .form-group .radio-group {
      display: flex;
      justify-content: space-between;
    }
  
    .form-group .radio-group label {
      flex: 1;
      padding: 10px;
      margin-right: 10px;
      border: 1px solid #ddd;
      border-radius: 4px;
      cursor: pointer;
      background-color: white;
      color: #3d4b51;
    }
  
    .form-group .radio-group label.active {
      border-color: #fbcf44;
      background-color: #f9f9f9;
    }
  
    .form-group .radio-group input {
      display: none;
    }
  
    .form-group .radio-group .description {
      font-size: 12px;
      color: #666;
    }
  
    .form-group .buttons {
      display: flex;
      justify-content: space-between;
    }
  
    .form-group .buttons button {
      flex: 1;
      padding: 10px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
    }
  
    .form-group .buttons .create {
      background-color: #fbcf44;
      color: #3d4b51;
      margin-right: 10px;
    }
  
    .form-group .buttons .create:hover {
      background-color: #e6b833;
    }
  
    .form-group .buttons .cancel {
      background-color: #3d4b51;
      color: white;
    }
  
    .form-group .buttons .cancel:hover {
      background-color: #232b2f;
    }
    .create-affiliatep {
		padding: 10px 20px;
		background: #3d4b51;
		color: #ffffff;
		border: none;
		border-radius: 5px;
		cursor: pointer;
	}
	.create-affiliatep:hover {
		background: #232b2f;
	}
  </style>
  
  <div class="form-container">
    <div class="form-group">
      <label for="player">Player</label>
      <select id="player" bind:value={player}>
        <option value="Onur Göksu - onurbey1">Onur Göksu - onurbey1</option>
        <!-- Add more options here if needed -->
      </select>
    </div>
  
    <div class="form-group">
      <label for="commissionRate">Rate</label>
      <input type="text" id="commissionRate" bind:value={commissionRate} placeholder="Commission rate" />
    </div>
  
    <div class="form-group">
      <label>Commission type</label>
      <div class="radio-group">
        <label class:active={commissionType === 'revenue'}>
          <input type="radio" name="commissionType" value="revenue" bind:group={commissionType} />
          Revenue
          <div class="description">Revenue generated by the platform from the payment processing section of your affiliated members</div>
        </label>
        <label class:active={commissionType === 'deposit'}>
          <input type="radio" name="commissionType" value="deposit" bind:group={commissionType} />
          Deposit
          <div class="description">From the deposit made by your affiliate members. Merchant commissions will be deducted from the affiliate balance.</div>
        </label>
      </div>
    </div>
  
    <div class="form-group">
      <label for="network">Network</label>
      <select id="network" bind:value={network}>
        <option value="website">Website</option>
        <!-- Add more options here if needed -->
      </select>
    </div>
  
    <div class="form-group">
      <label for="networkLink">Network Link</label>
      <input type="text" id="networkLink" bind:value={networkLink} />
    </div>
  
    <div class="form-group buttons">
      <button class="create-affiliatep" on:click={createAffiliate}>Create affiliate</button>
      <!-- <button class="cancel" on:click={cancel}>Cancel</button> -->
    </div>
  </div>
  